### PR TITLE
always set an email for the comment

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@saeedmb8 @KaitCrawford review please
This is why the comments are not posting in QA and Prod - it complains that email is required. But for normal users, we don't ask them for their email so it borks.

**Comment by KaitCrawford** [comment]
@miltontony why is an email required in the first place?

**Comment by miltontony** [comment]
@KaitCrawford It's required by django_comments. They assume the user email is set.

**Comment by KaitCrawford** [comment]
@miltontony Ah ok. :+1:

**Pull request merged**
