### PR TITLE
fix the order of comments and replies

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@miltontony @hodgestar @rudigiesler ready for review

**Comment by hodgestar** [comment]
Hmm. Tests are failing?

**Comment by KaitCrawford** [comment]
I know exactly what's wrong and am really annoyed by it

**Comment by hodgestar** [comment]
Other than the failing tests, looks good.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
