### PR TITLE
TUNE-79: allow user in the 'Expert' group to reply to comments on the…

### PR DESCRIPTION
**Pull request by maltem-za**
… front-end

### CODE REVIEW

**Comment by maltem-za** [comment]
Note that because tuneme is overriding some of the molo.commenting templates, either comments/comment.html in tuneme needs to be updated or deleted (as it seems to be an exact copy of comment.html from molo.commenting anyway)

**Comment by smarzban** [comment]
@maltem-za yes, TuneMe templates need to be updated to mach the latest.

**Comment by smarzban** [comment]
@maltem-za can you please add tests :)

**Comment by smarzban** [comment]
We will add tests for this PR in issue #23

**Pull request merged**
