### PR TITLE
Allow commenting to be anonymous & add validation.

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
Ready for review.

**Comment by smn** [comment]
Now really ready for review @miltontony @saeedmb8 & @bruskiza

**Comment by smarzban** [comment]
@smn travis checks has failed otherwise a big :+1:

**Comment by smn** [comment]
tests now passing, it was waiting for `molo.core==2.4.1` to be available on pypi.python.org

**Comment by smarzban** [comment]
cool :+1:

**Pull request merged**
